sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer install
script:
  - vendor/bin/phpdoc -d src/ -t phpdocs/
  #- zip -r "Sdk-Ris-Php-6.5.7.zip" . -x vendor/\* -x build/\* -x phpdocs/\* -x .git/\* sdkphp/
after_script:
  - if [ -n "$GH_TOKEN" ]; then $GH_TOKEN; fi;
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAGG=$(awk -F "=" '/SDK_VERSION/ {print $2}' src/settings.ini)
  - echo $GIT_TAGG
  - git tag -a $GIT_TAGG -m 'Version for git tag.'
  - git push --quiet https://$GH_TOKEN@github.com/preslav-anev/test-ris-php-sdk.git $GIT_TAGG > /dev/null 2>&1
branches:
  except:
    - /^[0-9].*/

#deploy:
#  provider: releases
#  api_key: $GH_TOKEN
#  file: Sdk-Ris-Php-6.5.8.zip
#  skip_cleanup: true
#  on:
#    branch: master
notifications:
  email:
    recipients:
      - preslavanev@abv.bg