language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script: composer install
script:
  - vendor/bin/phpdoc
after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push --tags
notifications:
  email:
    recipients:
      - preslavanev@abv.bg
