language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script: composer install
script:
  - vendor/bin/phpdoc
after_script:
  - git config --global user.email "preslav.anev@sirma.bg"
  - git config --global user.name "preslav-anev"
  - git config --global credential.helper cache
  - export GIT_TAG=0.1.$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG
  - git tag -a $GIT_TAG -m 'Version $VERS'
  - git push origin --tags
notifications:
  email:
    recipients:
      - preslavanev@abv.bg

branches:
  except:
    - /^build-[0-9a-z\-]*/