language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script: composer install
script:
  - vendor/bin/phpdoc
after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag -a "First tag" -m "Generating tag from Travis CI"
  - git push --tags
notifications:
  email:
    recipients:
      - preslavanev@abv.bg
