language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script: composer install
script:
  - vendor/bin/phpdoc
after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=0.1.$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG
  - git tag -a $GIT_TAG -m 'Version $VERS'
  - git push --quiet https://<token>@github.com/preslav-anev/test-ris-php-sdk.git --tags
notifications:
  email:
    recipients:
      - preslavanev@abv.bg

branches:
  except:
    - /^build-[0-9a-z\-]*/