sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer install
script:
  - vendor/bin/phpdoc -d src/ -t phpdocs/
  #- git update-index --chmod=+x release.sh
  - ./release.sh
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAGG=$(awk -F "=" '/SDK_VERSION/ {print $2}' src/settings.ini)
  - echo $GIT_TAGG
  - git tag -a $GIT_TAGG -m 'Version for git tag.'
  - git push --quiet https://$GH_TOKEN@github.com/preslav-anev/test-ris-php-sdk.git --tags > /dev/null 2>&1
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: Sdk-Ris-Php.zip
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
notifications:
  email:
    recipients:
      - preslavanev@abv.bg
