language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script: composer install
script:
  - vendor/bin/phpdoc
after_script:
   - ./gitTag.sh
#  - if [ -n "$GH_TOKEN" ]; then echo $GH_TOKEN; fi;
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - export GIT_TAG=0.1.$TRAVIS_BUILD_NUMBER
#  - echo $GIT_TAG
#  - git tag -a $GIT_TAG -m 'Version $GIT_TAG'
#  - git push --quiet https://$GH_TOKEN@github.com/preslav-anev/test-ris-php-sdk.git --tags > /dev/null 2>&1
#deploy:
#  - provider: releases
#  - api_key:
#      secure: ${GH_TOKEN}
#    file: "File to upload"
#    skip_cleanup: true
#    on:
#      tags: false
notifications:
  email:
    recipients:
      - preslavanev@abv.bg

#branches:
#  except:
#    - /^*[0-9]*/