sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer install
script:
  #- vendor/bin/phpdoc
after_script:
  - if [ -n "$GH_TOKEN" ]; then $GH_TOKEN; fi;
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=0.1.$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG
  - git tag -a $GIT_TAG -m 'Version $GIT_TAG'
  - git push --quiet https://$GH_TOKEN@github.com/preslav-anev/test-ris-php-sdk.git $GIT_TAG > /dev/null 2>&1
notifications:
  email:
    recipients:
      - preslavanev@abv.bg

branches:
  except:
    - /^[0-9].*/