sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer install
script:
  - vendor/bin/phpdoc -d src/ -t phpdocs/
after_script:
  - if [ -n "$GH_TOKEN" ]; then $GH_TOKEN; fi;
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=0.1.$TRAVIS_BUILD_NUMBER #This to be removed
  - export GIT_TAGG=$(awk -F "=" '/SDK_VERSION/ {print $2}' src/settings.ini)
  - echo $GIT_TAGG
  - git tag -a $GIT_TAGG -m 'Version $GIT_TAGG'
  - git push --quiet https://$GH_TOKEN@github.com/preslav-anev/test-ris-php-sdk.git $GIT_TAGG > /dev/null 2>&1
notifications:
  email:
    recipients:
      - preslavanev@abv.bg

branches:
  except:
    - /^[0-9].*/